apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litellm-app
  namespace: litellm
spec:
  project: default
  source:
    repoURL: oci://docker.litellm.ai/berriai/litellm-helm
    targetRevision: 1.81.12-stable.2
    chart: litellm-helm
  destination:
    server: https://kubernetes.default.svc
    namespace: litellm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
